databases:
  - name: voltworthdb
    plan: free
    databaseName: voltworth
    user: voltworth

services:
  - type: web
    plan: free
    name: voltworth
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn voltworth_config.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: voltworthdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
